
account_name: aatuu
data_dir: ./data
cache_dir: ./cache
cookie_file: ./cookie.txt
cookie_max_age_days: 1
base_url: "https://{account_name}.substack.com"
timeout: 30
headers:
  User-Agent: "Mozilla/5.0"

posts:
  url: "api/v1/posts"
  pagination: offset
  limit: 20
  sort_key: id
  exclude:
    - body_html
    - publishedBylines
    - truncated_body_text
  _include:
    - id
    - post_date
    - updated_at
    - title
    - slug
    - canonical_url
    - subtitle
    - audience
    - type
    - is_published
    - wordcount
    - reactions
    - reaction_count
    - comment_count
    - child_comment_count
    - restacks
    - section_id
    - language

users:
  url: "api/v1/publication/users/ranked"
  sort_key: id
  params:
    public: true
  _include:
    - id
    - handle
    - name
    - bio
    - photo_url

subscribers:
  url: "api/v1/subscriber-stats"
  method: post
  pagination: offset
  limit: 50
  items_field: subscribers
  sort_key: subscription_created_at
  use_cookie: true
  body:
    filters:
      order_by_desc_nulls_last: subscription_created_at
    includeTags: true
  exclude:
    - user_photo_url

notes:
  url: "https://substack.com/api/v1/reader/feed/profile/{user_id}"
  pagination: cursor
  cursor_field: nextCursor
  items_field: items
  sort_key: entity_key
  dependencies:
    user_id: users.[0].id
  exclude:
    - context:
      - users
    - post:
      - publishedBylines
    - trackingParameters
  _include:
    - entity_key
    - context:
        - source
        - timestamp
        - type
        - page_rank
    - post:
        - id
        - post_date
        - title
        - truncated_body_text
        - reaction_count
        - restacks
        - comment_count
        - child_comment_count
        - audience
        - type
        - wordcount
        - canonical_url
