
account_name: aatuu
data_dir: ./data
base_url: "https://{account_name}.substack.com"
timeout: 30
headers:
  User-Agent: "Mozilla/5.0"

posts:
  url: "api/v1/posts"
  pagination: offset
  limit: 20
  columns:
    - id
    - post_date
    - updated_at
    - title
    - slug
    - canonical_url
    - subtitle
    - audience
    - type
    - is_published
    - wordcount
    - reactions
    - reaction_count
    - comment_count
    - child_comment_count
    - restacks
    - section_id
    - language

users:
  url: "api/v1/publication/users/ranked"
  params:
    public: true

notes:
  url: "https://substack.com/api/v1/reader/feed/profile/{user_id}"
  pagination: cursor
  cursor_field: nextCursor
  items_field: items
  dependencies:
    user_id: users.[0].id
